#ifndef _GENERATE_H_
#define _GENERATE_H_


namespace Generate {

	enum EPARSESTATUS {
		SUCCESS = 0,
		OPEN_FILE_FAILED,
		ERROR_FILE_SIZE,
		CREATE_FILE_MAPPING_ERROR,
		MAP_FILE_ERROR,
		NOT_A_PE_FILE,
		ERROR_PROGRAM_BITNESS,
		NO_EXPORT_TABLE,
		FIND_EXPORT_TABLE_FAILED,
		NO_EXPORT_FUNCTIONS
	};

	EPARSESTATUS Parse(const char* FileName);
}

#endif // !_GENERATE_H_

